/* eslint-disable no-new-wrappers, unicorn/new-for-builtins */

export const Values: Record<string, () => any> = {
  '0': () => 0,
  'new Number(0)': () => new Number(0),
  '1': () => 1,
  'new Number(1)': () => new Number(1),
  'NaN': () => Number.NaN,
  'Infinity': () => Infinity,
  '-Infinity': () => -Infinity,
  '0.1 + 0.2': () => 0.1 + 0.2,
  '0.3': () => 0.3,
  '1e18': () => 1e18,
  '1e18 - 1': () => 1e18 - 1,
  'true': () => true,
  'new Boolean(1)': () => new Boolean(1),
  'false': () => false,
  'new Boolean(0)': () => new Boolean(0),
  'undefined': () => undefined,
  'null': () => null,
  '""': () => '',
  '"\\t"': () => '\t',
  '"s"': () => 's',
  'new String()': () => new String(),
  'new String("s")': () => new String('s'),
  'new String("\\t")': () => new String('\t'),
  '[]': () => [],
  '{}': () => ({}),
  'new Date(1145)': () => new Date(1145),
  'new Object("s")': () => new Object('s'),
};
